# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'AZURE_TO_SONAR_2'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'jalugoqu_prueba_AYAAufzpYfStsm0BZxBD'
    cliProjectName: 'demo'
    cliSources: '.'
    extraProperties: |
      sonar.sources=src
      sonar.exclusions=**/node_modules/**,src/assets/**
      sonar.javascript.lcov.reportPaths=coverage/demo/lcov-report/lcov.info
      sonar.tests=src
      sonar.test.inclusions=**/*.spec.ts

- task: SonarQubeAnalyze@5
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
